theme = "peach"

[editor]
scrolloff = 5
mouse = true
middle-click-paste = false
scroll-lines = 3
shell = ["nu", "-c"]
line-number = "absolute"
cursorline = false
cursorcolumn = false
auto-completion = true
auto-format = false
auto-save = true
idle-timeout = 500
completion-timeout = 5
preview-completion-insert = false
completion-trigger-len = 2
completion-replace = true
auto-info = true
true-color = true
undercurl = true
bufferline = "always"
color-modes = true
text-width = 100
workspace-lsp-roots = []
default-line-ending = "native"
insert-final-newline = true
popup-border = "all"
indent-heuristic = "hybrid"

[editor.gutters]
layout = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator", "version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "register", "position", "file-encoding"]

[editor.lsp]
enable = true
display-messages = false
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false
follow-symlinks = true
deduplicate-links = true
parents = true
ignore = true
git-ignore = true
git-global = true
git-exclude = true

[editor.search]
smart-case = true
wrap-around = true

[editor.indent-guides]
render = true
character = "│"
skip-levels = 1

[keys.insert]
"C-left" = ["move_prev_word_start", "collapse_selection"]
"C-right" = ["move_next_word_start", "move_char_right"]
"C-h" = "delete_word_backward"
"C-del" = "delete_word_forward"
"A-x" = "normal_mode"

[keys.normal]
"C-left" = ["move_prev_word_start", "collapse_selection"]
"C-right" = ["move_next_word_start", "move_char_right"]
"C-s" = [":w", ":sh cargo fmt", ":rl"]

[keys.select]
"C-left" = "move_prev_word_start"
"C-right" = "move_next_word_start"
