theme = "peach"

[editor]
scrolloff = 5
mouse = true
middle-click-paste = false
scroll-lines = 3
shell = ["pwsh", "-c"]
line-number = "relative"
cursorline = false
cursorcolumn = false
auto-completion = true
auto-format = true
auto-save = true
idle-timeout = 500
completion-timeout = 5
preview-completion-insert = false
completion-trigger-len = 2
completion-replace = true
auto-info = true
true-color = true
undercurl = true
bufferline = "always"
color-modes = true
text-width = 100
workspace-lsp-roots = []
default-line-ending = "native"
insert-final-newline = true
popup-border = "all"
indent-heuristic = "hybrid"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.gutters]
layout = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator", "version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "register", "position", "file-encoding"]

[editor.lsp]
enable = true
display-messages = false
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false
follow-symlinks = true
deduplicate-links = true
parents = true
ignore = true
git-ignore = true
git-global = true
git-exclude = true

[editor.search]
smart-case = true
wrap-around = true

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[keys.insert]
"C-left" = ["move_prev_word_start", "collapse_selection"]
"C-right" = ["move_next_word_start", "move_char_right"]
"C-backspace" = "delete_word_backward"
"C-del" = "delete_word_forward"
"home" = "goto_first_nonwhitespace"
"A-x" = "normal_mode"
"C-s" = ":w"
"C-S-s" = ":w!"

[keys.normal]
"C-left" = ["move_prev_word_start", "collapse_selection"]
"C-right" = ["move_next_word_start", "move_char_right"]
"C-h" = ["move_prev_word_start", "collapse_selection"]
"C-l" = ["move_next_word_start", "move_char_right"]
"C-s" = ":w"
"C-S-s" = ":w!"
"pagedown" = ["move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down"]
"pageup" = ["move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up"]
"C-j" = ["move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down"]
"C-k" = ["move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up"]
"A-j" = ["move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down"]
"A-k" = ["move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up"]
"home" = "goto_first_nonwhitespace"
"A-h" = "goto_first_nonwhitespace"
"A-l" = "goto_line_end"
"p" = "paste_before"
"P" = "paste_after"

"C-down" = ["move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down"]
"C-up" = ["move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up"]

"C-S-up" = ["select_mode", "copy_selection_on_prev_line", "normal_mode"]
"C-S-down" = ["select_mode", "copy_selection_on_next_line", "normal_mode"]

"S-home" = ["select_mode", "goto_first_nonwhitespace", "normal_mode"]
"S-end" = ["select_mode", "goto_line_end", "normal_mode"]

"S-up" = ["extend_visual_line_up"]
"S-down" = ["extend_visual_line_down"]

"C-S-right" = ["extend_next_word_end"]
"C-S-left" = ["extend_prev_word_start"]

"S-right" = ["extend_char_right"]
"S-left" = ["extend_char_left"]

"C-c" = ["yank_to_clipboard"]

[keys.normal.space]
"\\" = "goto_next_buffer"
"tab" = "goto_previous_buffer"
"q" = ":bc"
"Q" = ":bc!"

[keys.normal.space.w]
"w" = "jump_view_up"
"a" = "jump_view_left"
"s" = "jump_view_down"
"d" = "jump_view_right"
"minus" = "hsplit"
"+" = "vsplit"

[keys.select]
"C-left" = "move_prev_word_start"
"C-right" = "move_next_word_start"
