"attribute" = { fg = "attributes", modifiers = ["italic"] }
"type" = { fg = "typename", modifiers = ["italic"] }
"type.builtin" = { fg = "keyword", modifiers = ["bold"] }
"type.parameter" = { fg = "typename", modifiers = ["italic"] }
"type.enum" = "enums"
"type.enum.variant" = { fg = "typename", modifiers = ["italic"] }
"constructor" = "functions"
"constant" = "constant_vars"
"constant.builtin" = "keyword"
"constant.character" = "chars"
"constant.character.escape" = "string_escape_seq"
"constant.numeric" = "numbers"
"string" = "strings"
"string.regexp" = "chars"
"string.special.url" = "mdlink"
"comment" = { fg = "attributes", modifiers = ["italic"] }
"comment.line" = { fg = "disabled_code", modifiers = ["italic"] } 
"variable" = "vars"
"variable.builtin" = "keyword"
"variable.parameter" = { fg = "vars", modifiers = ["italic"] }
"variable.other" = "invalid"
"variable.other.member" = { fg = "vars", modifiers = ["italic"] }
"label" = { fg = "vars", modifiers = ["italic"] }
"punctuation" = "operator"
# "punctuation.bracket" = "white"
"punctuation.special" = "string_escape_seq"
"keyword" = "keyword"
# "keyword.storage.modifier" = "mutable_vars"
"operator" = "operator"
"function" = "functions"
"function.method" = "functions"
"function.macro" = { fg = "macros", modifiers = ["italic"] }
"tag" = "vars"
"namespace" = "typename"
"special" = "functions"

"markup.heading" = "mdheading"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "mdlink", modifiers = ["underlined"] }

"ui.cursor" = { bg = "secondary_cursor" }
"ui.cursor.primary" = { bg = "cursor" }
"ui.selection" = { bg = "cursor_select", underline.style = "line" }
# "ui.popup" = { bg = "menus" }
# "ui.popup.info" = "white"
# "ui.menu" = { bg = "menus" }
"ui.menu.selected" = { bg = "cursor" }
"ui.debug.breakpoint" = "error"
"ui.debug.active" = "warning"
"ui.gutter.selected" = { fg = "#262226", bg = "#826482" }
"ui.statusline" = { fg = "statusline" }
"ui.statusline.inactive" = { bg = "default" }
"ui.statusline.normal" = { bg = "palette_blue" }
"ui.statusline.insert" = { bg = "palette_cyan" }
"ui.statusline.select" = { bg = "palette_green" }
"ui.virtual.indent-guide" = "inlay_hints"
"ui.virtual.inlay-hint" = "inlay_hints"
"ui.virtual.jump-label" = { modifiers = ["bold"], underline = { color = "invalid", style = "dotted" } }

"ui.bufferline.active" = { bg = "palette_grey" }

"error" = "error"
"info" = "info"
"warning" = "warning"

"diagnostic" = { underline = { color = "diagnostic", style = "curl" } }
"diagnostic.hint" = { underline = { color = "info", style = "curl" } }
"diagnostic.info" = { underline = { color = "info", style = "curl" } }
"diagnostic.warning" = { underline = { color = "warning", style = "curl" } }
"diagnostic.error" = { underline = { color = "error", style = "curl" } }

"diff.plus" = "palette_green"
"diff.minus" = "palette_blue"
"diff.delta" = "palette_yellow"

[palette]
keyword = "#569CD6"
attributes = "#57A64A"
typename = "#43C9B0"
operator = "#C586C0"
enums = "#83C98E"
constant_vars = "#C89691"
vars = "#9CDCFE"
functions = "#EFEFA9"
strings = "#CEC291"
chars = "#CE9178"
numbers = "#B5CEA8"
traits = "#A9D797"
macros = "#DDD463"
mutable_vars = "#D6C9FE"
unsafe = "#5856D6"
usnafe_fn = "#FF8D00"
string_escape_seq = "#B5CEA8"
invalid_string_escape_seq = "#C800B6"
disabled_code = "#526544"
inlay_hints = "#AAAAAA"
indent_guide = "#333333"

mdcode = "#CE9178"
mdheading = "#9393CC"
mdlink = "#AED4FE"

secondary_cursor = "#875BAE"
cursor = "#AE5B5B"
cursor_select = "#486363"

invalid = "#ff00ff"

warning = "#A8C023"
error = "#BC3F3C"
info = "#9CDCFE"
diagnostic = "#403e40"
diag_warn = "#515B11"
diag_err = "#5B1E1D"
diag_info = "#394C5B"

menus = "#303030"

palette_blue = "#3E4975"
palette_cyan = "#3C6772"
palette_green = "#3B703E"
palette_yellow = "#828446"
palette_grey = "#686868"

statusline = "#9CC2FE"
